BeautyBusiness/Controllers/AdminAlbumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BeautyBusiness.DataAccess;
using BeautyBusiness.Models;
using System.IO;

namespace BeautyBusiness.Controllers.Admin
{
    public class AdminAlbumsController : Controller
    {

        AlbumService objAlbumModelService = new AlbumService();
        BeautyServices bs = new BeautyServices();
        // GET: AdminAlbums
        public ActionResult Index()
        {

            ViewBag.total = objAlbumModelService.GetAlbums().ToList().Count;
            return View(objAlbumModelService.GetAlbums().ToList());

           // return View();
        }
        [HttpGet]
        public ActionResult AddImage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddImage(FormCollection collection)
        {
            HttpPostedFileBase file = Request.Files["ImageData"];
            AlbumMaster objAlbumMaster = new AlbumMaster();
            objAlbumMaster.ImageName = collection["ImageName"].ToString();
            objAlbumMaster.SubServiceID = Convert.ToInt32(collection["subservicelist"].ToString());
            objAlbumMaster.Image = ConvertToBytes(file);
            objAlbumModelService.UploadAlbums(objAlbumMaster);
            return RedirectToAction("Index");
        }

        public byte[] ConvertToBytes(HttpPostedFileBase image)
        {
            byte[] imageBytes = null;
            BinaryReader reader = new BinaryReader(image.InputStream);
            imageBytes = reader.ReadBytes((int)image.ContentLength);
            return imageBytes;
        }

        public string getServiceList()
        {
            List<Service> list = bs.GetServices();
            string output = "<option value=''>Select Service</option>";

            foreach(Service s in list)
            {
                output+="<option value='"+s.serviceId+"'>"+s.serviceName+"</option>";
            }



            return output;
        }

        public string getSubServiceList(int id)
        {

            List<subService> list = bs.GetSubServices(id);
            string output = "<option value=''>Select Sub Service</option>";

            foreach (subService s in list)
            {
                output += "<option value='" + s.subServiceId + "'>" + s.SubServiceName + "</option>";
            }

            return output;
        }


        public ActionResult RetrieveImage(int id)
        {
            byte[] cover = objAlbumModelService.GetImageFromDataBase(id);
            if (cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }
    }
}

BeautyBusiness/Views/AdminAlbums/AddImage.cshtml
@model BeautyBusiness.Models.AlbumMaster

@{
    ViewBag.Title = "AddImage";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="container-fluid">
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Manage Customer</li>
    </ol>
    <!-- Example DataTables Card-->



</div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>

    $(document).ready(function () {

        $.ajax({
            type: "get",
            url: "/AdminAlbums/getServiceList",           
            success: function (data) {
                $("#servicelist").html(data);
            }
        });


        $("#servicelist").change(function () {


            var sid = $("#servicelist").val();

            $.ajax({
                type: "get",
                url: "/AdminAlbums/getSubServiceList",
                data:{ id : sid },
                success: function (data) {
                    $("#subservicelist").html(data);
                }
            });

        });


    });



    function ValidateForm() {
        var txt1 = document.getElementById('ImageName');
        if (txt1.value == '') {
            alert("Enter Image Name !")
            document.getElementById("ImageName").focus();
            return false;
        }

        var txt2 = document.getElementById('subservicelist');
        if (txt2.value == '') {
            alert("Please select Image category or Sub category  !")
            document.getElementById("subservicelist").focus();
            return false;
        }


        var uploadfile = document.getElementById('ImageData');

        if (uploadfile.value == '') {
            alert('Please upload the attachment');
            uploadfile.focus();
            return false;
        }

        var fname = uploadfile.value;
        var ext = fname.split(".");
        var x = ext.length;
        var extstr = ext[x - 1].toLowerCase();
        if (extstr == 'jpg' || extstr == 'jpeg' || extstr == 'png' || extstr == 'gif') { }
        else {
            alert("Please upload valid image");
            uploadfile.focus();
            return false;
        }

        alert("Image uploaded sucessfully");
    }
</script>



<div class="container" style="border:2px solid red;">
    <h2>Add Album</h2>
   

@using (Html.BeginForm("AddImage", "AdminAlbums", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
{

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="form-group">
        <label class="control-label col-sm-2" for="email">Image Name:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="ImageName" placeholder="Enter Image Name" name="ImageName">
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2" for="email">Image </label>
        <div class="col-sm-10">
            <input type="file" class="form-control" id="ImageData" placeholder="select Image" name="ImageData">
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2" for="email">Select Service </label>
        <div class="col-sm-10">
           
            <select id="servicelist" name="servicelist"></select>

        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2" for="email">Select Sub Service </label>
        <div class="col-sm-10">

            <select id="subservicelist" name="subservicelist"></select>

        </div>
    </div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <input type="submit" name="submit" value="Upload" onclick="return ValidateForm()" />
        </div>
    </div>

}          
</div>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <br />
            <br />
            <a href="/AdminAlbums/Index?class=btn%20btn-info" class="btn btn-info">Back to AlbumList</a>
        </div>
    </div>
</div>

BeautyBusiness/Views/AdminAlbums/Index.cshtml
@model IEnumerable<BeautyBusiness.Models.AlbumMaster>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<style>
    .imageclass {
        max-width: 100%;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
    }

    .thumbmain {
        margin: 3px;
        border: 1px solid #A0ACC0;
        height: auto;
        float: left;
        text-align: center;
    }

    .thumbimg {
        display: inline;
        margin: 5px;
        border: 1px solid #A0ACC0;
    }
</style>



<div class="container-fluid">
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Manage Galary</li>
    </ol>
    <!-- Example DataTables Card-->



</div>


<div class="container">

    <a href="/AdminAlbums/AddImage" class="btn btn-info">Add Image</a>
    <br />
    <br />

    <table cellpadding="5" cellspacing="10" width="1100">
        @{
            //repeatdirection = Horizontal, RepeatColumns = 4
            const int NumberOfColumns = 4;
            int skip = 0;
            var items = Model.Skip(skip).Take(NumberOfColumns);
            while (items.Count() > 0)
            {
                <tr>
                    @foreach (var item in items)
                {
                        <td width="250" style="border:1px solid red;">
                            <table class="thumbmain">
                                <tr>
                                    <td>
                                        <img src="/AdminAlbums/RetrieveImage/@item.ImageId" width="200" height="150" class="imageclass" />
                                    </td>
                                </tr>
                                <tr>
                                    <td style="text-align: center; font-weight: bold; color: Teal">
                                        @item.ImageName
                                    </td>
                                </tr>
                            </table>
                        </td>
                    }
                </tr>
                skip += NumberOfColumns;
                items = Model.Skip(skip).Take(NumberOfColumns);
            }
        }
    </table>
</div>